# Site settings
title: Scond
SEOTitle: Scond的个人博客
email: zenjury@gmail.com
description: "跑步、阅读、旅行，一生的爱好。"
keyword: "跑步者, 旅行者, 读书人"
url: "https://blog.scond.me"
baseurl: ""
author: Scond

# Build settings
permalink: pretty
paginate: 5
exclude: ["README.md"]
plugins: [jekyll-paginate]

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd

# Friends
friends: [
    { title: "yihong0618", href: "https://github.com/yihong0618/gitblog" }
]

# Progressive Web App
chrome-tab-theme-color: "#C7952E"
service-worker: true
